// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('@arco-design/web-vue')['AutoComplete']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    AInputSearch: typeof import('@arco-design/web-vue')['InputSearch']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
  }
}

export { }
